/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import static hospital_management_system.JFrame_11.jLabel_Date;
import static hospital_management_system.JFrame_11.jLabel_Time;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_16 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_16
     */
    public JFrame_16() {
        initComponents();
        showTableData();
        showDate();
        showTime();
        Toolkit toolkit = getToolkit();//that last 3 rows use to form align center
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }
    
    
    //Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
            jLabel1_Time.setText(s.format(d));
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_Date_Of_Checked = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CMD_BACK = new javax.swing.JButton();
        CMD_ADD = new javax.swing.JButton();
        CMD_UPDATE = new javax.swing.JButton();
        CMD_SEARCH = new javax.swing.JButton();
        Tel_No = new javax.swing.JTextField();
        PID_TB = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        CMD_DELTE = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1_Time = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();
        D_Name_TB1 = new javax.swing.JTextField();
        P_Name_TB1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Print6 = new javax.swing.JMenu();
        jMenuItem_New1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem_Open_Cal = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Close1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Discharged patients details");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/user-arrow-left-icon.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Discharged patients details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 30, 980, 60);

        jDateChooser_Date_Of_Checked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser_Date_Of_Checked.setDateFormatString("MMM dd, yyyy");
        jPanel1.add(jDateChooser_Date_Of_Checked);
        jDateChooser_Date_Of_Checked.setBounds(250, 360, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Patient Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 230, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Doctor's Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 290, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date Of Last Checked :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 350, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Telephone Number :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 410, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address :");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 470, 120, 30);

        CMD_BACK.setBackground(new java.awt.Color(0, 84, 140));
        CMD_BACK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMD_BACK.setForeground(new java.awt.Color(255, 255, 255));
        CMD_BACK.setText("<<Back");
        CMD_BACK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CMD_BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMD_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMD_BACKActionPerformed(evt);
            }
        });
        jPanel1.add(CMD_BACK);
        CMD_BACK.setBounds(20, 540, 120, 40);

        CMD_ADD.setBackground(new java.awt.Color(0, 84, 140));
        CMD_ADD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMD_ADD.setForeground(new java.awt.Color(255, 255, 255));
        CMD_ADD.setText("Add");
        CMD_ADD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CMD_ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMD_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMD_ADDActionPerformed(evt);
            }
        });
        jPanel1.add(CMD_ADD);
        CMD_ADD.setBounds(190, 540, 120, 40);

        CMD_UPDATE.setBackground(new java.awt.Color(0, 84, 140));
        CMD_UPDATE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMD_UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        CMD_UPDATE.setText("Update");
        CMD_UPDATE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CMD_UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMD_UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMD_UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(CMD_UPDATE);
        CMD_UPDATE.setBounds(520, 540, 120, 40);

        CMD_SEARCH.setBackground(new java.awt.Color(0, 84, 140));
        CMD_SEARCH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMD_SEARCH.setForeground(new java.awt.Color(255, 255, 255));
        CMD_SEARCH.setText("Search");
        CMD_SEARCH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CMD_SEARCH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMD_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMD_SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(CMD_SEARCH);
        CMD_SEARCH.setBounds(840, 540, 120, 40);

        Tel_No.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Tel_No);
        Tel_No.setBounds(250, 420, 190, 30);

        PID_TB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(PID_TB);
        PID_TB.setBounds(250, 180, 190, 30);

        Address.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Address);
        Address.setBounds(250, 480, 190, 30);

        CMD_DELTE.setBackground(new java.awt.Color(0, 84, 140));
        CMD_DELTE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CMD_DELTE.setForeground(new java.awt.Color(255, 255, 255));
        CMD_DELTE.setText("Delete");
        CMD_DELTE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CMD_DELTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CMD_DELTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMD_DELTEActionPerformed(evt);
            }
        });
        jPanel1.add(CMD_DELTE);
        CMD_DELTE.setBounds(360, 540, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Discharged ID :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 170, 150, 40);

        jLabel1_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_Time.setText("Time :-");
        jPanel1.add(jLabel1_Time);
        jLabel1_Time.setBounds(30, 110, 240, 30);

        jButton_Clear.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(680, 540, 120, 40);

        D_Name_TB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(D_Name_TB1);
        D_Name_TB1.setBounds(250, 300, 190, 30);

        P_Name_TB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(P_Name_TB1);
        P_Name_TB1.setBounds(250, 240, 190, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoscrolls(false);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(470, 180, 490, 330);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(700, 120, 240, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Java Projects\\Hospital_Management_System\\Images\\ix6vOA.jpg")); // NOI18N
        jLabel1.setDoubleBuffered(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 10, 980, 580);

        jMenu_Print6.setText("File");

        jMenuItem_New1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_New1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/New-file-icon.png"))); // NOI18N
        jMenuItem_New1.setText("New");
        jMenuItem_New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_New1jMenuItem_NewActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem_New1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Printer-icon.png"))); // NOI18N
        jMenuItem2.setText("Print");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem2);

        jMenuItem_Open_Cal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Open_Cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Scientific-calculator-icon.png"))); // NOI18N
        jMenuItem_Open_Cal.setText("Open Calculator");
        jMenuItem_Open_Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Open_CalActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem_Open_Cal);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Home-icon.png"))); // NOI18N
        jMenuItem1.setText("Go Back to Home Page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem1);
        jMenu_Print6.add(jSeparator1);

        jMenuItem_Close1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Exit-icon.png"))); // NOI18N
        jMenuItem_Close1.setText("Close");
        jMenuItem_Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Close1ActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem_Close1);
        jMenu_Print6.add(jSeparator2);

        jMenuItem1_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Logout-icon.png"))); // NOI18N
        jMenuItem1_logout.setText("Logout");
        jMenuItem1_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_logoutActionPerformed(evt);
            }
        });
        jMenu_Print6.add(jMenuItem1_logout);

        jMenuBar1.add(jMenu_Print6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMD_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMD_BACKActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_CMD_BACKActionPerformed

    private void CMD_UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMD_UPDATEActionPerformed

        if (PID_TB.getText().trim().isEmpty() && P_Name_TB1.getText().trim().isEmpty() && D_Name_TB1.getText().trim().isEmpty() && Tel_No.getText().trim().isEmpty() && Address.getText().trim().isEmpty() && (jDateChooser_Date_Of_Checked.getDate() == null)) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if ((jDateChooser_Date_Of_Checked.getDate() == null)) {  // It use only JdayChooser

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (PID_TB.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (P_Name_TB1.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (D_Name_TB1.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (Address.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "UPDATE retired_patients_details SET Patient_Name=? ,Doctor_Name=? ,Date_Of_Last_Checked=? ,Telephone_Number=? ,Address=? WHERE Patient_ID=?";//query wka ewnass wenawa ekinekata

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(6, PID_TB.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(1, P_Name_TB1.getText());
                pst.setString(2, D_Name_TB1.getText());

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateChooser_Date_Of_Checked.getDate());
                pst.setString(3, date);//Date Chhoser eken date ekaa add kirima

                pst.setString(4, Tel_No.getText());
                pst.setString(5, Address.getText());
                pst.executeUpdate();

                System.out.println(query);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Updated Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_16.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            P_Name_TB1.setText(null);
            PID_TB.setText(null);
            D_Name_TB1.setText(null);
            jDateChooser_Date_Of_Checked.setDate(null);
            Tel_No.setText(null);
            Address.setText(null);
            PID_TB.grabFocus();

        }
        showTableData();
    }//GEN-LAST:event_CMD_UPDATEActionPerformed

    private void CMD_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMD_ADDActionPerformed

        if (PID_TB.getText().trim().isEmpty() && P_Name_TB1.getText().trim().isEmpty() && D_Name_TB1.getText().trim().isEmpty() && Tel_No.getText().trim().isEmpty() && Address.getText().trim().isEmpty() && (jDateChooser_Date_Of_Checked.getDate() == null)) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if ((jDateChooser_Date_Of_Checked.getDate() == null)) {  // It use only JdayChooser

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (PID_TB.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (P_Name_TB1.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (D_Name_TB1.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (Tel_No.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (Address.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "INSERT INTO retired_patients_details(Patient_ID, Patient_Name, Doctor_Name, Date_Of_Last_Checked, Telephone_Number, Address)VALUES(?,?,?,?,?,?)";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, PID_TB.getText());
                pst.setString(2, P_Name_TB1.getText());
                pst.setString(3, D_Name_TB1.getText());

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateChooser_Date_Of_Checked.getDate());
                pst.setString(4, date);//Date Chhoser eken date ekaa add kirima

                pst.setString(5, Tel_No.getText());
                pst.setString(6, Address.getText());
                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Inserted Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_16.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            P_Name_TB1.setText(null);
            PID_TB.setText(null);
            D_Name_TB1.setText(null);
            jDateChooser_Date_Of_Checked.setDate(null);
            Tel_No.setText(null);
            Address.setText(null);
            PID_TB.grabFocus();

        }

        showTableData();
    }//GEN-LAST:event_CMD_ADDActionPerformed

    private void CMD_DELTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMD_DELTEActionPerformed

        if (PID_TB.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the Patient_ID before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that record in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (a == 0) {

                    String query = "DELETE FROM retired_patients_details WHERE Patient_ID=?";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, PID_TB.getText());
                    pst.executeUpdate();

                    P_Name_TB1.setText(null);
                    PID_TB.setText(null);
                    D_Name_TB1.setText(null);
                    jDateChooser_Date_Of_Checked.setDate(null);
                    Tel_No.setText(null);
                    Address.setText(null);
                    PID_TB.grabFocus();

                    System.out.println(pst);
                    System.out.println("1 row affected");

                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                }
                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_16.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                PID_TB.setText(null);
                PID_TB.grabFocus();
            }

        }
        showTableData();
    }//GEN-LAST:event_CMD_DELTEActionPerformed

    private void CMD_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMD_SEARCHActionPerformed

        if (PID_TB.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the Patient_ID before Search data.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                System.out.println(PID_TB.getText());
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                con = DriverManager.getConnection(url + db, user, pword);

                String sql = "SELECT * FROM retired_patients_details WHERE Patient_ID = '" + PID_TB.getText() + "'";

                ResultSet res = con.createStatement().executeQuery(sql);
                System.out.println(sql);

                while (res.next()) {

                    /* System.out.println(res.getString("Patient_Name"));
                System.out.println(res.getString("Doctor_Name"));*/
                    P_Name_TB1.setText(res.getString("Patient_Name"));
                    D_Name_TB1.setText(res.getString("Doctor_Name"));
                    Tel_No.setText(res.getString("Telephone_Number"));
                    Address.setText(res.getString("Address"));
                    jDateChooser_Date_Of_Checked.setDate(res.getDate("Date_Of_Last_Checked"));

                    System.out.println(res.getString("Patient_ID") + " " + res.getString("Patient_Name") + " " + res.getString("Date_Of_Last_Checked"));
                    System.out.println("Row Affected");
                }

                con.close();

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

                Logger.getLogger(JFrame_16.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                P_Name_TB1.setText(null);
                PID_TB.setText(null);
                D_Name_TB1.setText(null);
                jDateChooser_Date_Of_Checked.setDate(null);
                Tel_No.setText(null);
                Address.setText(null);
                PID_TB.grabFocus();

            }

        }
        showTableData();
    }//GEN-LAST:event_CMD_SEARCHActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed

//        if (PID_TB.getText().trim().isEmpty() && P_Name_TB1.getText().trim().isEmpty() && D_Name_TB1.getText().trim().isEmpty() && Tel_No.getText().trim().isEmpty() && Address.getText().trim().isEmpty() && (jDateChooser_Date_Of_Checked.getDate() == null)) {
//            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
        int a;

        a = JOptionPane.showConfirmDialog(null, "Are you sure to you went to clear data?", "Clear Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            P_Name_TB1.setText(null);
            PID_TB.setText(null);
            D_Name_TB1.setText(null);
            jDateChooser_Date_Of_Checked.setDate(null);
            Tel_No.setText(null);
            Address.setText(null);
            PID_TB.grabFocus();
        }

        showTableData();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

//TABALES SHOULD BE ENABLED FIRST
        int rows = jTable1.getRowCount();

        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String pid = jTable1.getValueAt(row_selected, 0).toString();
            String p_Name = jTable1.getValueAt(row_selected, 1).toString();
            String D_Name = jTable1.getValueAt(row_selected, 2).toString();
            Object date = jTable1.getValueAt(row_selected, 3);
            String tel_No = jTable1.getValueAt(row_selected, 4).toString();
            String address = jTable1.getValueAt(row_selected, 5).toString();

            PID_TB.setText(pid);
            P_Name_TB1.setText(p_Name);
            D_Name_TB1.setText(D_Name);
            jDateChooser_Date_Of_Checked.setDate((java.util.Date) date);
            Tel_No.setText(tel_No);
            Address.setText(address);

        } else {

            JOptionPane.showMessageDialog(null, rows);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_New1jMenuItem_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_New1jMenuItem_NewActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you save that data?", "Go to new form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            P_Name_TB1.setText(null);
            PID_TB.setText(null);
            D_Name_TB1.setText(null);
            jDateChooser_Date_Of_Checked.setDate(null);
            Tel_No.setText(null);
            Address.setText(null);
            PID_TB.grabFocus();
        }
    }//GEN-LAST:event_jMenuItem_New1jMenuItem_NewActionPerformed

    private void jMenuItem_Open_CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Open_CalActionPerformed

        JFrame_18 f18 = new JFrame_18();
        f18.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Open_CalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Close1ActionPerformed

        int b;
        b = JOptionPane.showConfirmDialog(null, "Are you sure to close the program now?", "Close the program...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (b == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem_Close1ActionPerformed

    private void jMenuItem1_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_logoutActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you want to logout the program.", "Logout the system.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (a == 0) {

            this.dispose();
            JFrame_10 f10 = new JFrame_10();
            f10.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem1_logoutActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.dispose();
        JFrame_32 f32 = new JFrame_32();
        f32.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "hospital_management_system_database";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String query = "SELECT * FROM retired_patients_details;";

            PreparedStatement pst = con.prepareStatement(query);
            ResultSet res = con.createStatement().executeQuery(query);

            pst = con.prepareStatement(query);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Address;
    private javax.swing.JButton CMD_ADD;
    private javax.swing.JButton CMD_BACK;
    private javax.swing.JButton CMD_DELTE;
    private javax.swing.JButton CMD_SEARCH;
    private javax.swing.JButton CMD_UPDATE;
    public static javax.swing.JTextField D_Name_TB1;
    public static javax.swing.JTextField PID_TB;
    public static javax.swing.JTextField P_Name_TB1;
    public static javax.swing.JTextField Tel_No;
    private javax.swing.JButton jButton_Clear;
    public static com.toedter.calendar.JDateChooser jDateChooser_Date_Of_Checked;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel1_Time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel_Date;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_logout;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_Close1;
    private javax.swing.JMenuItem jMenuItem_New1;
    private javax.swing.JMenuItem jMenuItem_Open_Cal;
    private javax.swing.JMenu jMenu_Print6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
