/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_26 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_26
     */
    public JFrame_26() {
        initComponents();
        showTableData();
        showDate();
        showTime();

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);

        Operations operations = new Operations();
        operations.listPersondata(jTable1, this);
    }
    
//Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
                jLabel1_Time.setText(s.format(d));
            }

        }).start();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3_Search_icon = new javax.swing.JLabel();
        JLabel_Status_text = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1_Time = new javax.swing.JLabel();
        JTextfield_NIC_No = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Date = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();
        jLabel3_Show_user = new javax.swing.JLabel();
        jButton_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        jMenu_new_user = new javax.swing.JMenuItem();
        jMenuItem_update_user = new javax.swing.JMenuItem();
        jMenuItem_Delete_User = new javax.swing.JMenuItem();
        jMenu_Option = new javax.swing.JMenu();
        jMenuItem_Pre_Window = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User's Personal Information");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/View user.png"))
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel3_Search_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_Search_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Search-icon.png"))); // NOI18N
        jLabel3_Search_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3_Search_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_Search_iconMouseClicked(evt);
            }
        });
        jLabel3_Search_icon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3_Search_iconKeyPressed(evt);
            }
        });
        jPanel1.add(jLabel3_Search_icon);
        jLabel3_Search_icon.setBounds(442, 180, 32, 30);

        JLabel_Status_text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabel_Status_text.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(JLabel_Status_text);
        JLabel_Status_text.setBounds(180, 210, 260, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("V");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(420, 180, 20, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User's Personal Information");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 780, 50);

        jLabel1_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_Time.setText("Time :-");
        jPanel1.add(jLabel1_Time);
        jLabel1_Time.setBounds(20, 120, 240, 30);

        JTextfield_NIC_No.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JTextfield_NIC_No.setForeground(new java.awt.Color(153, 153, 153));
        JTextfield_NIC_No.setText("search");
        JTextfield_NIC_No.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTextfield_NIC_No.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextfield_NIC_NoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTextfield_NIC_NoFocusLost(evt);
            }
        });
        JTextfield_NIC_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTextfield_NIC_NoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextfield_NIC_NoKeyTyped(evt);
            }
        });
        jPanel1.add(JTextfield_NIC_No);
        JTextfield_NIC_No.setBounds(180, 180, 260, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Search User :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 180, 140, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIC_No", "Usename", "Password", "Re_Enter_Password", "phone_number", "Full_name", "Date_Of_Birth", "Gender", "image_path"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentX(1.0F);
        jTable1.setAlignmentY(1.0F);
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 250, 710, 180);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Date.setText("Date :-");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(550, 120, 230, 29);

        jButton_Back.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(40, 610, 120, 40);

        jLabel3_Show_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3_Show_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_Show_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jLabel3_Show_user);
        jLabel3_Show_user.setBounds(290, 440, 250, 180);

        jButton_Close.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Close.setText("Close");
        jButton_Close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Close);
        jButton_Close.setBounds(630, 610, 120, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Java Projects\\Hospital_Management_System\\Images\\shutterstock_1462012334.jpg")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 770, 650);

        JMenu1.setText("File");

        jMenu_new_user.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenu_new_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Actions-list-add-user-icon-1.png"))); // NOI18N
        jMenu_new_user.setText("Add New User");
        jMenu_new_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_new_userActionPerformed(evt);
            }
        });
        JMenu1.add(jMenu_new_user);

        jMenuItem_update_user.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_update_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Male-user-edit-icon.png"))); // NOI18N
        jMenuItem_update_user.setText("Update User Account");
        jMenuItem_update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_update_userActionPerformed(evt);
            }
        });
        JMenu1.add(jMenuItem_update_user);

        jMenuItem_Delete_User.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Delete_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Actions-list-remove-user-icon-1.png"))); // NOI18N
        jMenuItem_Delete_User.setText("Delete User Account");
        jMenuItem_Delete_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Delete_UserActionPerformed(evt);
            }
        });
        JMenu1.add(jMenuItem_Delete_User);

        jMenuBar1.add(JMenu1);

        jMenu_Option.setText("Option");

        jMenuItem_Pre_Window.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Pre_Window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/arrow-back-icon.png"))); // NOI18N
        jMenuItem_Pre_Window.setText("Open Previous Window");
        jMenuItem_Pre_Window.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Pre_WindowActionPerformed(evt);
            }
        });
        jMenu_Option.add(jMenuItem_Pre_Window);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Exit-icon.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_Option.add(jMenuItem1);
        jMenu_Option.add(jSeparator2);

        jMenuItem1_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Logout-icon.png"))); // NOI18N
        jMenuItem1_logout.setText("Logout");
        jMenuItem1_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_logoutActionPerformed(evt);
            }
        });
        jMenu_Option.add(jMenuItem1_logout);

        jMenuBar1.add(jMenu_Option);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        jLabel3_Show_user.setText("<<Dispaly the user's picture here.>>");

    }//GEN-LAST:event_formWindowOpened

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed

        int a;
        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit?", "Exit the details form.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {
            this.dispose();

        }

    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jMenu_new_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_new_userActionPerformed

        JFrame_19 f19 = new JFrame_19();
        f19.setVisible(true);

    }//GEN-LAST:event_jMenu_new_userActionPerformed

    private void jMenuItem_update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_update_userActionPerformed

        JFrame_22 f22 = new JFrame_22();
        f22.setVisible(true);

    }//GEN-LAST:event_jMenuItem_update_userActionPerformed

    private void jMenuItem_Delete_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Delete_UserActionPerformed

        JFrame_24 f24 = new JFrame_24();
        f24.setVisible(true);

    }//GEN-LAST:event_jMenuItem_Delete_UserActionPerformed

    private void jMenuItem1_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_logoutActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you want to logout the admin panel.", "Logout from admin panel.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            this.dispose();
            JFrame_10 f10 = new JFrame_10();
            f10.setVisible(true);

        }

    }//GEN-LAST:event_jMenuItem1_logoutActionPerformed

    private void jMenuItem_Pre_WindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Pre_WindowActionPerformed

        this.dispose();
        JFrame_23 f23 = new JFrame_23();
        f23.setVisible(true);

    }//GEN-LAST:event_jMenuItem_Pre_WindowActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JTextfield_NIC_NoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextfield_NIC_NoKeyTyped

        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {

            evt.consume();
            getToolkit().beep();
            JLabel_Status_text.setText("Please enter only numbers.");
        }

    }//GEN-LAST:event_JTextfield_NIC_NoKeyTyped

    private void JTextfield_NIC_NoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextfield_NIC_NoKeyPressed

        JLabel_Status_text.setText(null);

        String searchTxtStr = JTextfield_NIC_No.getText();
        if (!searchTxtStr.isEmpty()) {

            String query = "SELECT * FROM useres WHERE NIC_No LIKE '%" + searchTxtStr + "%'";
            Operations operations = new Operations();//operation class file
            operations.searchPersonData(query, JLabel_Status_text, jTable1, this);

        } else {
            JLabel_Status_text.setText("Please enter the ID to search.");
        }

        //It use for work the enter button.
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            JLabel_Status_text.setText(null);
        }

    }//GEN-LAST:event_JTextfield_NIC_NoKeyPressed

    private void JTextfield_NIC_NoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextfield_NIC_NoFocusGained

        //That is clear the text felds and show "username".
        String search = String.valueOf(JTextfield_NIC_No.getText());

        if (search.trim().toLowerCase().equals("search")) {

            JTextfield_NIC_No.setText(null);
            JTextfield_NIC_No.setForeground(Color.BLACK);

        }


    }//GEN-LAST:event_JTextfield_NIC_NoFocusGained

    private void JTextfield_NIC_NoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextfield_NIC_NoFocusLost

        String src = String.valueOf(JTextfield_NIC_No.getText());

        if (src.trim().equals("") || JTextfield_NIC_No.getText().trim().toLowerCase().equals("search")) {

            JTextfield_NIC_No.setText("search");
            JTextfield_NIC_No.setForeground(new Color(153, 153, 153));//me code eken apita kamthi patak add karanna puluwan
        }

    }//GEN-LAST:event_JTextfield_NIC_NoFocusLost

    private void jLabel3_Search_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_Search_iconMouseClicked

        String searchTxtStr = JTextfield_NIC_No.getText();
        if (!searchTxtStr.isEmpty()) {

            String query = "SELECT * FROM useres WHERE NIC_No LIKE '%" + searchTxtStr + "%'";
            Operations operations = new Operations();
            operations.searchPersonData(query, JLabel_Status_text, jTable1, this);

        } else {
            JLabel_Status_text.setText("Please enter the ID to search.");
        }

    }//GEN-LAST:event_jLabel3_Search_iconMouseClicked

    private void jLabel3_Search_iconKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3_Search_iconKeyPressed
//Connect with Opperations.java class file

        JLabel_Status_text.setText(null);

        //It use for work the enter button.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String searchTxtStr = JTextfield_NIC_No.getText();
            if (!searchTxtStr.isEmpty()) {

                String query = "SELECT * FROM useres WHERE NIC_No LIKE '%" + searchTxtStr + "%'";
                Operations operations = new Operations();//operation class file
                operations.searchPersonData(query, JLabel_Status_text, jTable1, this);

            } else {
                JLabel_Status_text.setText("Please enter the ID to search.");
            }
        }

    }//GEN-LAST:event_jLabel3_Search_iconKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

//Code for set image of selrcted raw 
        int rows = jTable1.getRowCount();

        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String img_path = jTable1.getValueAt(row_selected, 8).toString();

            ImageIcon image = new ImageIcon(img_path);
            image = new ImageIcon(image.getImage().getScaledInstance(260, 180, BufferedImage.SCALE_SMOOTH));
            jLabel3_Show_user.setIcon(image);  // where jLabel2 is your label

        }

    }//GEN-LAST:event_jTable1MouseClicked

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "hospital_management_system_database";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String query = "SELECT * FROM useres;";

            PreparedStatement pst = con.prepareStatement(query);
            ResultSet res = con.createStatement().executeQuery(query);

            pst = con.prepareStatement(query);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

            getToolkit().beep();
            JOptionPane.showMessageDialog(null, ex, "Connection Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_26.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_26.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_26.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_26.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JLabel_Status_text;
    private javax.swing.JMenu JMenu1;
    public static javax.swing.JTextField JTextfield_NIC_No;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1_Time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_Search_icon;
    private javax.swing.JLabel jLabel3_Show_user;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_logout;
    private javax.swing.JMenuItem jMenuItem_Delete_User;
    private javax.swing.JMenuItem jMenuItem_Pre_Window;
    private javax.swing.JMenuItem jMenuItem_update_user;
    private javax.swing.JMenu jMenu_Option;
    private javax.swing.JMenuItem jMenu_new_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
