/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Flags;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_27 extends javax.swing.JFrame {
    
    int randomCode;

    /**
     * Creates new form JFrame_27
     */
    public JFrame_27() {
        initComponents();

        //set the form location in the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //Add the border.
        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);

        // Add border and give colour for the minmize & close buttons.
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Miniimize.setBorder(Lable__Border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Miniimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Verification = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jButton_Verify = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jButton_Send = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jLabel_Verify_Email = new javax.swing.JLabel();
        jLabel_val_verification_code = new javax.swing.JLabel();
        jButton_Close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send and Verify code");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/global-icon.png"))
        );
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Semt your verification Code");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 610, 40);

        jLabel_Miniimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Miniimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Miniimize.setText("-");
        jLabel_Miniimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Miniimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Miniimize);
        jLabel_Miniimize.setBounds(560, 10, 30, 30);

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Close);
        jLabel_Close.setBounds(590, 10, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email Address :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Verification Code :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 300, 170, 30);

        jTextField_Verification.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Verification.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Verification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_VerificationKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_VerificationKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_Verification);
        jTextField_Verification.setBounds(190, 290, 260, 40);

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Email);
        jTextField_Email.setBounds(190, 160, 260, 40);

        jButton_Verify.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Verify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Verify.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Verify.setText("Verify");
        jButton_Verify.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Verify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerifyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Verify);
        jButton_Verify.setBounds(480, 290, 120, 40);

        jButton_Back.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(40, 400, 120, 40);

        jButton_Send.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Send.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Send.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Send.setText("Send");
        jButton_Send.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Send);
        jButton_Send.setBounds(480, 160, 120, 40);

        jButton_Clear.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(260, 400, 120, 40);

        jLabel_Verify_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Verify_Email.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Verify_Email);
        jLabel_Verify_Email.setBounds(190, 210, 260, 30);

        jLabel_val_verification_code.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_val_verification_code.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_val_verification_code);
        jLabel_val_verification_code.setBounds(190, 340, 260, 30);

        jButton_Close.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Close.setText("Close");
        jButton_Close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Close);
        jButton_Close.setBounds(480, 400, 120, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/2018-02-27healthcare-data-security.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 610, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_MiniimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseClicked
        
        this.setState(JFrame_1.ICONIFIED);

    }//GEN-LAST:event_jLabel_MiniimizeMouseClicked

    private void jLabel_MiniimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseEntered
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.WHITE);

    }//GEN-LAST:event_jLabel_MiniimizeMouseEntered

    private void jLabel_MiniimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseExited
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.BLACK);

    }//GEN-LAST:event_jLabel_MiniimizeMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        
        int a;
        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit the program?", "Close the program?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == 0) {
            
            this.dispose();
            
        }

    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.WHITE);

    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited
        
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.BLACK);

    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jButton_VerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerifyActionPerformed
        
        if (jTextField_Verification.getText().trim().isEmpty()) {
            
            jLabel_val_verification_code.setText("Please enter the veification code.");
            
        } else {
            
            if (Integer.valueOf(jTextField_Verification.getText()) == randomCode) {
                
                JFrame_28 f28 = new JFrame_28(jTextField_Email.getText());
                this.dispose();
                f28.setVisible(true);
                
            } else {
                
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Verification code is dosen't matched.", "Verification unsuccsessfully...", JOptionPane.ERROR_MESSAGE);
                jTextField_Verification.setText(null);
                
            }
        }
    }//GEN-LAST:event_jButton_VerifyActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        
        JFrame_25 f25 = new JFrame_25();
        f25.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendActionPerformed
       
        // https://myaccount.google.com/lesssecureapps?gar=1 me link ekata gihin less secure app enable karanna kalinma.
                
        if (jTextField_Email.getText().trim().isEmpty()) {
            
            jLabel_Verify_Email.setText("Please enter the admin's email.");
            
        } else {
            
            try {
                
                Random rand = new Random();
                randomCode = rand.nextInt(999999);
                String host = "smtp.gmail.com";
                String user = "stanneshospitalplc@gmail.com";
                String pass = "trustme@everyday.778590";
                String to = jTextField_Email.getText();
                String subject = "Forgot the administrator password in the St. Anne's Hospital Management System. - For verify your account.-";
                String link = "https://www.facebook.com/mysorestannes";
                String message = "Your verification code is" + " " + randomCode + ".";
                boolean sessionDebug = false;
                
                Properties pros = System.getProperties();
                pros.put("mail.smtp.host", "host");
                pros.put("mail.smtp.port", "465");
                pros.put("mail.smtp.auth", "true");
                pros.put("mail.smtp.socketFactory.port", "465");
                pros.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                
                java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                Session mailSession = Session.getDefaultInstance(pros, null);
                mailSession.setDebug(sessionDebug);
                
                Message msg = new MimeMessage(mailSession);
                msg.setFrom(new InternetAddress(user));
                InternetAddress[] address = {new InternetAddress(to)};
                msg.setRecipients(Message.RecipientType.TO, address);
                msg.setSubject(subject);
                msg.setSentDate(new Date());
                msg.setFlag(Flags.Flag.FLAGGED, sessionDebug);
                msg.setText(message + " " + "You can join with us from our facebook page now." + " "+ link + " " + "Thank You!!!");
                
                Transport transport = mailSession.getTransport("smtp");
                transport.connect(host, user, pass);
                transport.sendMessage(msg, msg.getAllRecipients());
                transport.close();
                
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Your verification code is send to the email.", "Send your code", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (HeadlessException | MessagingException ex) {
                
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, ex, "System Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                JFrame_25 f25 = new JFrame_25();
                f25.setVisible(true);
            }
            
        }

    }//GEN-LAST:event_jButton_SendActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        
        jTextField_Email.setText(null);
        jTextField_Verification.setText(null);
        jLabel_Verify_Email.setText(null);
        jLabel_Verify_Email.setText(null);
        jLabel_val_verification_code.setText(null);
        jTextField_Email.grabFocus();

    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        jTextField_Email.grabFocus();

    }//GEN-LAST:event_formWindowOpened

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
        
        int a;
        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit the program?", "Close the program?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (a == 0) {
            
            this.dispose();
            
        }

    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jTextField_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyPressed
        
        jLabel_Verify_Email.setText(null);

    }//GEN-LAST:event_jTextField_EmailKeyPressed

    private void jTextField_VerificationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VerificationKeyPressed
        
        jLabel_val_verification_code.setText(null);

    }//GEN-LAST:event_jTextField_VerificationKeyPressed

    private void jTextField_VerificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_VerificationKeyTyped
      
    //Numbers only  
    
    char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            
            evt.consume();
            getToolkit().beep();
            jLabel_val_verification_code.setText("You can enter only numberes in this field.");
        }

    }//GEN-LAST:event_jTextField_VerificationKeyTyped

    private void jTextField_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyReleased
       
             //Email Validation
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(jTextField_Email.getText());

        if (!match.matches()) {

            jLabel_Verify_Email.setText("Email is incorrect.");

        } else {

            jLabel_Verify_Email.setText(null);

        }

        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {

            jLabel_Verify_Email.setText(null);

        }
        
    }//GEN-LAST:event_jTextField_EmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_27().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_Send;
    private javax.swing.JButton jButton_Verify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Miniimize;
    private javax.swing.JLabel jLabel_Verify_Email;
    private javax.swing.JLabel jLabel_val_verification_code;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Verification;
    // End of variables declaration//GEN-END:variables
}
