/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_23 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_23
     */
    public JFrame_23() {
        initComponents();
        showDate();
        showTime();
        //set the form location in the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //Add the border.
        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);

        // Add border and give colour for the minmize & close buttons.
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Miniimize.setBorder(Lable__Border);

    }
    
//Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
                jLabel1_Time.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1_Time = new javax.swing.JLabel();
        jButton_Remove_User = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jButton_Add_User1 = new javax.swing.JButton();
        jButton_User_Control1 = new javax.swing.JButton();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Miniimize = new javax.swing.JLabel();
        jButton_View_User_Details = new javax.swing.JButton();
        jLabel_Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Accounts Control Setting");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/groups-icon.png"))
        );
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Account Control");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 600, 33);

        jLabel1_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_Time.setText("Time :-");
        jPanel1.add(jLabel1_Time);
        jLabel1_Time.setBounds(30, 120, 240, 30);

        jButton_Remove_User.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Remove_User.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Remove_User.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Actions-list-remove-user-icon-1.png"))); // NOI18N
        jButton_Remove_User.setText("Remove Account");
        jButton_Remove_User.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Remove_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_UserActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Remove_User);
        jButton_Remove_User.setBounds(150, 430, 270, 60);

        jButton_Logout.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Logout-icon.png"))); // NOI18N
        jButton_Logout.setText("Logout Admin");
        jButton_Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Logout);
        jButton_Logout.setBounds(150, 510, 270, 60);

        jButton_Add_User1.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Add_User1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Add_User1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_User1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Actions-list-add-user-icon-1_2.png"))); // NOI18N
        jButton_Add_User1.setText("Add New Account");
        jButton_Add_User1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Add_User1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_User1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_User1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add_User1);
        jButton_Add_User1.setBounds(150, 350, 270, 60);

        jButton_User_Control1.setBackground(new java.awt.Color(0, 84, 140));
        jButton_User_Control1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_User_Control1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_User_Control1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Male-user-edit-icon.png"))); // NOI18N
        jButton_User_Control1.setText("Update User Account");
        jButton_User_Control1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_User_Control1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_User_Control1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_User_Control1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_User_Control1);
        jButton_User_Control1.setBounds(150, 190, 270, 60);

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Close);
        jLabel_Close.setBounds(570, 10, 30, 30);

        jLabel_Miniimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Miniimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Miniimize.setText("-");
        jLabel_Miniimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Miniimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Miniimize);
        jLabel_Miniimize.setBounds(540, 10, 30, 30);

        jButton_View_User_Details.setBackground(new java.awt.Color(0, 84, 140));
        jButton_View_User_Details.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_View_User_Details.setForeground(new java.awt.Color(255, 255, 255));
        jButton_View_User_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/View user.png"))); // NOI18N
        jButton_View_User_Details.setText("View User Details");
        jButton_View_User_Details.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_View_User_Details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_View_User_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_View_User_DetailsActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_View_User_Details);
        jButton_View_User_Details.setBounds(150, 270, 270, 60);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Date.setText("Date :-");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(360, 120, 230, 29);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\My Java Projects\\Hospital_Management_System\\Images\\20190911_111255.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 590, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Remove_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_UserActionPerformed

        JFrame_24 f24 = new JFrame_24();
        f24.setVisible(true);

    }//GEN-LAST:event_jButton_Remove_UserActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you want to logout the admin panel.", "Logout from admin panel.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            JFrame_25 f25 = new JFrame_25();
            f25.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jButton_User_Control1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_User_Control1ActionPerformed

        JFrame_22 f22 = new JFrame_22();
        f22.setVisible(true);

    }//GEN-LAST:event_jButton_User_Control1ActionPerformed

    private void jButton_View_User_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_View_User_DetailsActionPerformed

        JFrame_26 f26 = new JFrame_26();
        f26.setVisible(true);

    }//GEN-LAST:event_jButton_View_User_DetailsActionPerformed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked

        int a;

        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit the Login Form?", "Close the Lgin Form?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {
            this.dispose();

        }
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_MiniimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseClicked

        this.setState(JFrame_1.ICONIFIED);
    }//GEN-LAST:event_jLabel_MiniimizeMouseClicked

    private void jLabel_MiniimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_MiniimizeMouseEntered

    private void jLabel_MiniimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_MiniimizeMouseExited

    private void jButton_Add_User1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_User1ActionPerformed

        JFrame_19 f19 = new JFrame_19();
        f19.setVisible(true);

    }//GEN-LAST:event_jButton_Add_User1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_23.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_23().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_User1;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_Remove_User;
    private javax.swing.JButton jButton_User_Control1;
    private javax.swing.JButton jButton_View_User_Details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Miniimize;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
