/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_24 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_24
     */
    public JFrame_24() {
        initComponents();
        showDate();
        showTime();
        
     //set the form location in the screen.
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //Add the border.
        Border JPanel_title__Border = BorderFactory.createMatteBorder(7, 7, 7, 7, Color.black);
        jPanel1.setBorder(JPanel_title__Border);

        // Add border and give colour for the minmize & close buttons.
        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Miniimize.setBorder(Lable__Border);
    }

    //Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
                jLabel1_Time.setText(s.format(d));
            }
        }).start();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1_Time = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Miniimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_NIC_No = new javax.swing.JTextField();
        jLabel_Val_NIC_NO = new javax.swing.JLabel();
        jButton_Clr = new javax.swing.JButton();
        jButton_Back1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove your Account");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/Actions-list-remove-user-icon-1.png"))
        );
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Remove the User Account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 660, 40);

        jLabel1_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_Time.setText("Time :-");
        jPanel1.add(jLabel1_Time);
        jLabel1_Time.setBounds(30, 120, 240, 30);

        jButton_Delete.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(290, 330, 120, 40);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Date.setText("Date :-");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(450, 120, 230, 29);

        jLabel_Miniimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Miniimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Miniimize.setText("-");
        jLabel_Miniimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Miniimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Miniimize);
        jLabel_Miniimize.setBounds(610, 10, 30, 30);

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabel_Close);
        jLabel_Close.setBounds(640, 10, 30, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("NIC No :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 210, 80, 22);

        jTextField_NIC_No.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_NIC_No.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_NIC_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_NIC_NoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NIC_NoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_NIC_No);
        jTextField_NIC_No.setBounds(250, 210, 250, 30);

        jLabel_Val_NIC_NO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Val_NIC_NO.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel_Val_NIC_NO);
        jLabel_Val_NIC_NO.setBounds(250, 250, 280, 30);

        jButton_Clr.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Clr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clr.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clr.setText("Clear");
        jButton_Clr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClrActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clr);
        jButton_Clr.setBounds(490, 330, 120, 40);

        jButton_Back1.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back1.setText("<<Back");
        jButton_Back1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back1);
        jButton_Back1.setBounds(70, 330, 120, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(500, 210, 20, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/wallpapertip_blue-design-wallpaper_794437.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 660, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_NIC_No.getText().trim().isEmpty()) {

//            getToolkit().beep();
//
//          JOptionPane.showMessageDialog(null, "You should enter the your N.I.C Number before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
            jLabel_Val_NIC_NO.setText("You must enter the your N.I.C Number.");

        } else {

            try {

                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver

                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that user in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (a == 0) {

                    String query = "DELETE FROM useres WHERE NIC_No=?";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, jTextField_NIC_No.getText());
                    pst.executeUpdate();

                    jTextField_NIC_No.setText(null);
                    jLabel_Val_NIC_NO.setText(null);
                    jTextField_NIC_No.grabFocus();;

                    System.out.println(pst);
                    System.out.println("1 row affected");

                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessfully...");
              
                }
                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

            } catch (IllegalAccessException | InstantiationException ex) {

                Logger.getLogger(JFrame_24.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_NIC_No.setText(null);
                jLabel_Val_NIC_NO.setText(null);
                jTextField_NIC_No.grabFocus();

            }

        }

    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTextField_NIC_NoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NIC_NoKeyTyped

       char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_ENTER)) {

            evt.consume();
            getToolkit().beep();
            jLabel_Val_NIC_NO.setText("Please enter only numbers.");
        }
        
    }//GEN-LAST:event_jTextField_NIC_NoKeyTyped

    private void jButton_ClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClrActionPerformed

        jTextField_NIC_No.setText(null);
        jLabel_Val_NIC_NO.setText(null);
        jTextField_NIC_No.grabFocus();

    }//GEN-LAST:event_jButton_ClrActionPerformed

    private void jButton_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton_Back1ActionPerformed

    private void jTextField_NIC_NoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NIC_NoKeyPressed

        jLabel_Val_NIC_NO.setText(null);

        //It use for work the enter button.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jTextField_NIC_No.getText().trim().isEmpty()) {

//            getToolkit().beep();
//
//            JOptionPane.showMessageDialog(null, "You should enter the your N.I.C Number before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);
                jLabel_Val_NIC_NO.setText("You must enter the your N.I.C Number.");

            } else {

                try {

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = "jdbc:mysql://localhost:3306/";
                    String db = "hospital_management_system_database";
                    String user = "root";
                    String pword = "123456";

                    Connection con = null;
                    con = DriverManager.getConnection(url + db, user, pword);

                    int a;
                    a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that user in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                    if (a == 0) {

                        String query = "DELETE FROM useres WHERE NIC_No=?";

                        PreparedStatement pst = con.prepareStatement(query);

                        pst.setString(1, jTextField_NIC_No.getText());
                        pst.executeUpdate();

                        jTextField_NIC_No.setText(null);
                        jLabel_Val_NIC_NO.setText(null);
                        jTextField_NIC_No.grabFocus();;

                        System.out.println(pst);
                        System.out.println("1 row affected");

                        JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                    } else {

                        JOptionPane.showMessageDialog(null, "System Can not find the record in database.", "Record Delete Unsuccsessfully...", JOptionPane.ERROR_MESSAGE);
                    }

                    con.close();

                } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                    Logger.getLogger(JFrame_24.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex);

                    jTextField_NIC_No.setText(null);
                    jLabel_Val_NIC_NO.setText(null);
                    jTextField_NIC_No.grabFocus();
                }

            }

        }
    }//GEN-LAST:event_jTextField_NIC_NoKeyPressed

    private void jLabel_MiniimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseClicked

        this.setState(JFrame_1.ICONIFIED);
    }//GEN-LAST:event_jLabel_MiniimizeMouseClicked

    private void jLabel_MiniimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_MiniimizeMouseEntered

    private void jLabel_MiniimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_MiniimizeMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked

        int a;
        getToolkit().beep();
        a = JOptionPane.showConfirmDialog(null, "Are you sure to extit the delete account window?", "Close the delete account?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            this.dispose();

        }
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_CloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_24.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_24.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_24.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_24.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_24().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back1;
    private javax.swing.JButton jButton_Clr;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel1_Time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Miniimize;
    private javax.swing.JLabel jLabel_Val_NIC_NO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_NIC_No;
    // End of variables declaration//GEN-END:variables
}
