/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import static hospital_management_system.JFrame_11.jLabel_Date;
import static hospital_management_system.JFrame_11.jLabel_Time;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_15 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_15
     */
    public JFrame_15() {
        initComponents();
        showTableData();
        showDate();
        showTime();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }
    
    
    //Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
            jLabel_Time.setText(s.format(d));
        }).start();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jDateChooser_Date_Of_Last_Checked = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Resource_ID = new javax.swing.JTextField();
        jTextField_Beds = new javax.swing.JTextField();
        jTextField_Ambiulances = new javax.swing.JTextField();
        jTextField_Scanner_Machines = new javax.swing.JTextField();
        jTextField_Other_Fasilities = new javax.swing.JTextField();
        jButton_Back = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        jLabel_Date = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_New1 = new javax.swing.JMenuItem();
        jMenuItem_Open_Cal = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Close1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add resources of the hospital");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/Resourses medical-bed-icon.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resources of the hospital");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 960, 40);

        jLabel_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Time.setText("Time :");
        jPanel1.add(jLabel_Time);
        jLabel_Time.setBounds(40, 130, 220, 30);

        jDateChooser_Date_Of_Last_Checked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jDateChooser_Date_Of_Last_Checked);
        jDateChooser_Date_Of_Last_Checked.setBounds(260, 270, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Resource ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 210, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Beds :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 330, 60, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText(" Ambiulances :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 380, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Scanner Machines :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 440, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Other Fasilities :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 500, 150, 30);

        jTextField_Resource_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Resource_ID);
        jTextField_Resource_ID.setBounds(260, 210, 190, 30);

        jTextField_Beds.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Beds);
        jTextField_Beds.setBounds(260, 330, 190, 30);

        jTextField_Ambiulances.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Ambiulances);
        jTextField_Ambiulances.setBounds(260, 390, 190, 30);

        jTextField_Scanner_Machines.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Scanner_Machines);
        jTextField_Scanner_Machines.setBounds(260, 450, 190, 30);

        jTextField_Other_Fasilities.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Other_Fasilities);
        jTextField_Other_Fasilities.setBounds(260, 510, 190, 30);

        jButton_Back.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(30, 570, 120, 40);

        jButton_Add.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add.setText("Add");
        jButton_Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);
        jButton_Add.setBounds(180, 570, 120, 40);

        jButton_Delete.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(340, 570, 120, 40);

        jButton_Clear.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(660, 570, 120, 40);

        jButton_Search.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search.setText("Search");
        jButton_Search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Search);
        jButton_Search.setBounds(830, 570, 120, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Date of last Cheaked :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 270, 210, 22);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(490, 210, 460, 330);

        jButton_Update.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Update.setText("Update");
        jButton_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(500, 570, 120, 40);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Date.setText("Date :-");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(720, 130, 230, 29);

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setIcon(new javax.swing.ImageIcon("D:\\My Java Projects\\Hospital_Management_System\\Images\\Our Model  urbanhealthcare.com.au.jpg")); // NOI18N
        jPanel1.add(Image);
        Image.setBounds(10, 10, 960, 620);

        jMenu2.setText("File");

        jMenuItem_New1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_New1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/New-file-icon.png"))); // NOI18N
        jMenuItem_New1.setText("New");
        jMenuItem_New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_New1jMenuItem_NewActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_New1);

        jMenuItem_Open_Cal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Open_Cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Scientific-calculator-icon.png"))); // NOI18N
        jMenuItem_Open_Cal.setText("Open Calculator");
        jMenuItem_Open_Cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Open_CalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Open_Cal);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Home-icon.png"))); // NOI18N
        jMenuItem1.setText("Go Back to Home Page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem_Close1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Exit-icon.png"))); // NOI18N
        jMenuItem_Close1.setText("Close");
        jMenuItem_Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Close1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Close1);
        jMenu2.add(jSeparator2);

        jMenuItem1_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Logout-icon.png"))); // NOI18N
        jMenuItem1_logout.setText("Logout");
        jMenuItem1_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_logoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1_logout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty() && jTextField_Ambiulances.getText().trim().isEmpty() && jTextField_Beds.getText().trim().isEmpty() && jTextField_Other_Fasilities.getText().trim().isEmpty() && jTextField_Scanner_Machines.getText().trim().isEmpty() && (jDateChooser_Date_Of_Last_Checked.getDate() == null)) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if ((jDateChooser_Date_Of_Last_Checked.getDate() == null)) {  // It use only JdayChooser

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Ambiulances.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Beds.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Other_Fasilities.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Scanner_Machines.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "INSERT INTO resources_of_the_hospital(resource_ID, date_of_last_cheaked, Beds, ambiulances, scanner_machines, other_fasilities)VALUES(?,?,?,?,?,?)";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_Resource_ID.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateChooser_Date_Of_Last_Checked.getDate());
                pst.setString(2, date);//Date Chhoser eken date ekaa add kirima

                pst.setString(3, jTextField_Beds.getText());
                pst.setString(4, jTextField_Ambiulances.getText());
                pst.setString(5, jTextField_Scanner_Machines.getText());
                pst.setString(6, jTextField_Other_Fasilities.getText());
                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Inserted Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_15.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            jTextField_Ambiulances.setText(null);
            jTextField_Beds.setText(null);
            jDateChooser_Date_Of_Last_Checked.setDate(null);
            jTextField_Other_Fasilities.setText(null);
            jTextField_Resource_ID.setText(null);
            jTextField_Scanner_Machines.setText(null);
            jTextField_Resource_ID.grabFocus();

        }

        showTableData();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the Resource ID before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that record in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (a == 0) {

                    String query = "DELETE FROM resources_of_the_hospital WHERE resource_ID=?";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, jTextField_Resource_ID.getText());
                    pst.executeUpdate();

                    jTextField_Ambiulances.setText(null);
                    jTextField_Beds.setText(null);
                    jDateChooser_Date_Of_Last_Checked.setDate(null);
                    jTextField_Other_Fasilities.setText(null);
                    jTextField_Resource_ID.setText(null);
                    jTextField_Scanner_Machines.setText(null);
                    jTextField_Resource_ID.grabFocus();

                    System.out.println(pst);
                    System.out.println("1 row affected");

                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                }

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_15.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Resource_ID.setText(null);
                jTextField_Resource_ID.grabFocus();
                
            }

        }

        showTableData();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you went to clear the data?", "Clear Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            jTextField_Ambiulances.setText(null);
            jTextField_Beds.setText(null);
            jDateChooser_Date_Of_Last_Checked.setDate(null);
            jTextField_Other_Fasilities.setText(null);
            jTextField_Resource_ID.setText(null);
            jTextField_Scanner_Machines.setText(null);
            jTextField_Resource_ID.grabFocus();

        }
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty() && jTextField_Ambiulances.getText().trim().isEmpty() && jTextField_Beds.getText().trim().isEmpty() && jTextField_Other_Fasilities.getText().trim().isEmpty() && jTextField_Scanner_Machines.getText().trim().isEmpty() && (jDateChooser_Date_Of_Last_Checked.getDate() == null)) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if ((jDateChooser_Date_Of_Last_Checked.getDate() == null)) {  // It use only JdayChooser

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Resource_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Ambiulances.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Beds.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Other_Fasilities.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Scanner_Machines.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "UPDATE resources_of_the_hospital SET date_of_last_cheaked=? ,Beds=? ,ambiulances=? ,scanner_machines=? ,other_fasilities=? WHERE resource_ID=?";//query wka ewnass wenawa ekinekata

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(6, jTextField_Resource_ID.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateChooser_Date_Of_Last_Checked.getDate());
                pst.setString(1, date);//Date Chhoser eken date ekaa add kirima

                pst.setString(2, jTextField_Beds.getText());
                pst.setString(3, jTextField_Ambiulances.getText());
                pst.setString(4, jTextField_Scanner_Machines.getText());
                pst.setString(5, jTextField_Other_Fasilities.getText());
                pst.executeUpdate();

                System.out.println(query);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Updated Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_15.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            jTextField_Ambiulances.setText(null);
            jTextField_Beds.setText(null);
            jDateChooser_Date_Of_Last_Checked.setDate(null);
            jTextField_Other_Fasilities.setText(null);
            jTextField_Resource_ID.setText(null);
            jTextField_Scanner_Machines.setText(null);
            jTextField_Resource_ID.grabFocus();

        }
        showTableData();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed

        if (jTextField_Resource_ID.getText().trim().isEmpty() && jTextField_Ambiulances.getText().trim().isEmpty() && jTextField_Beds.getText().trim().isEmpty() && jTextField_Other_Fasilities.getText().trim().isEmpty() && jTextField_Scanner_Machines.getText().trim().isEmpty() && (jDateChooser_Date_Of_Last_Checked.getDate() == null)) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the Resource ID before Search data.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String url = "jdbc:mysql://localhost:3306/"; //url
                String db = "hospital_management_system_database"; //Database Name
                String user = "root";//user name
                String pword = "123456"; //password

                System.out.println(jTextField_Resource_ID.getText());//search kirimata yoda gannna textbox eke variabale name eka.
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver
                con = DriverManager.getConnection(url + db, user, pword);

                //SQL Query
                String sql = "SELECT * FROM resources_of_the_hospital WHERE resource_ID = '" + jTextField_Resource_ID.getText() + "'";

                ResultSet res = con.createStatement().executeQuery(sql);
                System.out.println(sql);

                while (res.next()) {

                    /* System.out.println(res.getString("Patient_Name"));
                System.out.println(res.getString("Doctor_Name"));*/
                    jTextField_Ambiulances.setText(res.getString("ambiulances"));  //Text feild wala names ewa form eke athi piliwelata yodanna.
                    jTextField_Beds.setText(res.getString("Beds"));
                    jDateChooser_Date_Of_Last_Checked.setDate(res.getDate("date_of_last_cheaked"));
                    jTextField_Other_Fasilities.setText(res.getString("other_fasilities"));
                    jTextField_Scanner_Machines.setText(res.getString("scanner_machines"));

                    System.out.println(res.getString("resource_ID") + " " + res.getDate("date_of_last_cheaked"));
                    System.out.println("Row Affected");
                    //Vadagthma field deke names yodanna.

                }

                con.close();//Connection eka close kirima.

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

                Logger.getLogger(JFrame_15.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Ambiulances.setText(null);
                jTextField_Beds.setText(null);
                jDateChooser_Date_Of_Last_Checked.setDate(null);
                jTextField_Other_Fasilities.setText(null);
                jTextField_Resource_ID.setText(null);
                jTextField_Scanner_Machines.setText(null);
                jTextField_Resource_ID.grabFocus();

            }

        }
        showTableData();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        //TABALES SHOULD BE ENABLED FIRST
        int rows = jTable1.getRowCount();

        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String res_id = jTable1.getValueAt(row_selected, 0).toString();
            Object date = jTable1.getValueAt(row_selected, 1);
            String beds = jTable1.getValueAt(row_selected, 2).toString();
            String ambiulance = jTable1.getValueAt(row_selected, 3).toString();
            String scanneres = jTable1.getValueAt(row_selected, 4).toString();
            String other_facilities = jTable1.getValueAt(row_selected, 5).toString();

            jTextField_Resource_ID.setText(res_id);
            jDateChooser_Date_Of_Last_Checked.setDate((java.util.Date) date);
            jTextField_Beds.setText(beds);
            jTextField_Ambiulances.setText(ambiulance);
            jTextField_Scanner_Machines.setText(scanneres);
            jTextField_Other_Fasilities.setText(other_facilities);
        } else {

            JOptionPane.showMessageDialog(null, rows);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_New1jMenuItem_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_New1jMenuItem_NewActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you save that data?", "Go to new form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

        jTextField_Ambiulances.setText(null);
            jTextField_Beds.setText(null);
            jDateChooser_Date_Of_Last_Checked.setDate(null);
            jTextField_Other_Fasilities.setText(null);
            jTextField_Resource_ID.setText(null);
            jTextField_Scanner_Machines.setText(null);
            jTextField_Resource_ID.grabFocus();
        }
    }//GEN-LAST:event_jMenuItem_New1jMenuItem_NewActionPerformed

    private void jMenuItem_Open_CalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Open_CalActionPerformed

        JFrame_18 f18 = new JFrame_18();
        f18.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Open_CalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Close1ActionPerformed

        int b;
        b = JOptionPane.showConfirmDialog(null, "Are you sure to close the program now?", "Close the program...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (b == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem_Close1ActionPerformed

    private void jMenuItem1_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_logoutActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you want to logout the program.", "Logout the system.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (a == 0) {

            this.dispose();
            JFrame_10 f10 = new JFrame_10();
            f10.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem1_logoutActionPerformed

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "hospital_management_system_database";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String query = "SELECT * FROM resources_of_the_hospital;";

            PreparedStatement pst = con.prepareStatement(query);
            ResultSet res = con.createStatement().executeQuery(query);

            pst = con.prepareStatement(query);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

            Logger.getLogger(JFrame_15.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Update;
    private com.toedter.calendar.JDateChooser jDateChooser_Date_Of_Last_Checked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_logout;
    private javax.swing.JMenuItem jMenuItem_Close1;
    private javax.swing.JMenuItem jMenuItem_New1;
    private javax.swing.JMenuItem jMenuItem_Open_Cal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Ambiulances;
    private javax.swing.JTextField jTextField_Beds;
    private javax.swing.JTextField jTextField_Other_Fasilities;
    private javax.swing.JTextField jTextField_Resource_ID;
    private javax.swing.JTextField jTextField_Scanner_Machines;
    // End of variables declaration//GEN-END:variables
}
