/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.border.Border;
/**
 *
 * @author Dinuwan Theekshana
 */
public class JFrame_13 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_13
     */
    public JFrame_13() {
        initComponents();
                     
        Border Lable__Border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Miniimize.setBorder(Lable__Border);
        
        jLabel_Close.setVisible(false);
        jLabel_Miniimize.setVisible(false);
    }
    double firstnum;
    double secondnum;
    double result;
    String operations;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_cal = new javax.swing.JTextField();
        jButton_Num1 = new javax.swing.JButton();
        jButton_Num3 = new javax.swing.JButton();
        jButton_Num2 = new javax.swing.JButton();
        jButton_Num5 = new javax.swing.JButton();
        jButton_Num6 = new javax.swing.JButton();
        jButton_Num7 = new javax.swing.JButton();
        jButton_Dot = new javax.swing.JButton();
        jButton_Num9 = new javax.swing.JButton();
        jButton_Num0 = new javax.swing.JButton();
        jButton_Num8 = new javax.swing.JButton();
        jButton_Num4 = new javax.swing.JButton();
        jButton_Clear_Calculator = new javax.swing.JButton();
        jButton_Sum = new javax.swing.JButton();
        jButton_Miness = new javax.swing.JButton();
        jButton_Substraction = new javax.swing.JButton();
        jButton_Devision = new javax.swing.JButton();
        jButton_Equal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton_Plua_Or_Miness = new javax.swing.JButton();
        jLabel_Miniimize = new javax.swing.JLabel();
        jLabel_Close = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Easy Calculator");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/Apps-Calculator-Metro-icon.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        txt_cal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txt_cal.setForeground(new java.awt.Color(153, 0, 102));
        txt_cal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txt_cal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_calKeyTyped(evt);
            }
        });

        jButton_Num1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num1.setText("1");
        jButton_Num1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num1ActionPerformed(evt);
            }
        });

        jButton_Num3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num3.setText("3");
        jButton_Num3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num3ActionPerformed(evt);
            }
        });

        jButton_Num2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num2.setText("2");
        jButton_Num2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num2ActionPerformed(evt);
            }
        });

        jButton_Num5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num5.setText("5");
        jButton_Num5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num5ActionPerformed(evt);
            }
        });

        jButton_Num6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num6.setText("6");
        jButton_Num6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num6ActionPerformed(evt);
            }
        });

        jButton_Num7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num7.setText("7");
        jButton_Num7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num7ActionPerformed(evt);
            }
        });

        jButton_Dot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Dot.setText(".");
        jButton_Dot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DotActionPerformed(evt);
            }
        });

        jButton_Num9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num9.setText("9");
        jButton_Num9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num9ActionPerformed(evt);
            }
        });

        jButton_Num0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num0.setText("0");
        jButton_Num0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num0ActionPerformed(evt);
            }
        });

        jButton_Num8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num8.setText("8");
        jButton_Num8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num8ActionPerformed(evt);
            }
        });

        jButton_Num4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Num4.setText("4");
        jButton_Num4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Num4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Num4ActionPerformed(evt);
            }
        });

        jButton_Clear_Calculator.setBackground(new java.awt.Color(255, 204, 204));
        jButton_Clear_Calculator.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Clear_Calculator.setText("C");
        jButton_Clear_Calculator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear_Calculator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear_Calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear_CalculatorActionPerformed(evt);
            }
        });

        jButton_Sum.setBackground(new java.awt.Color(51, 51, 255));
        jButton_Sum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Sum.setText("+");
        jButton_Sum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Sum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SumActionPerformed(evt);
            }
        });

        jButton_Miness.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Miness.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Miness.setText("-");
        jButton_Miness.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Miness.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Miness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MinessActionPerformed(evt);
            }
        });

        jButton_Substraction.setBackground(new java.awt.Color(255, 0, 255));
        jButton_Substraction.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Substraction.setText("*");
        jButton_Substraction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Substraction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Substraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubstractionActionPerformed(evt);
            }
        });

        jButton_Devision.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Devision.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Devision.setText("/");
        jButton_Devision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Devision.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Devision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DevisionActionPerformed(evt);
            }
        });

        jButton_Equal.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Equal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Equal.setText("=");
        jButton_Equal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Equal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EqualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("CASIO");

        jButton_Plua_Or_Miness.setBackground(new java.awt.Color(153, 102, 0));
        jButton_Plua_Or_Miness.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Plua_Or_Miness.setText("+/-");
        jButton_Plua_Or_Miness.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Plua_Or_Miness.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Plua_Or_Miness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Plua_Or_MinessActionPerformed(evt);
            }
        });

        jLabel_Miniimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Miniimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Miniimize.setText("-");
        jLabel_Miniimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Miniimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MiniimizeMouseExited(evt);
            }
        });

        jLabel_Close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close.setText("X");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Clear_Calculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_cal)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Miness, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Substraction, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton_Num8, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                        .addComponent(jButton_Num4, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                        .addComponent(jButton_Devision, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                    .addComponent(jButton_Plua_Or_Miness, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Miniimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Miniimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addComponent(txt_cal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Sum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Miness, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Substraction, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Plua_Or_Miness, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Devision, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear_Calculator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton_Back.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num1ActionPerformed

        String a = txt_cal.getText() + jButton_Num1.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num1ActionPerformed

    private void jButton_Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num3ActionPerformed

        String a = txt_cal.getText() + jButton_Num3.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num3ActionPerformed

    private void jButton_Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num2ActionPerformed

        String a = txt_cal.getText() + jButton_Num2.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num2ActionPerformed

    private void jButton_Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num5ActionPerformed

        String a = txt_cal.getText() + jButton_Num5.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num5ActionPerformed

    private void jButton_Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num6ActionPerformed
        String a = txt_cal.getText() + jButton_Num6.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num6ActionPerformed

    private void jButton_Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num7ActionPerformed
        String a = txt_cal.getText() + jButton_Num7.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num7ActionPerformed

    private void jButton_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DotActionPerformed
        String a = txt_cal.getText() + jButton_Dot.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_DotActionPerformed

    private void jButton_Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num9ActionPerformed
        String a = txt_cal.getText() + jButton_Num9.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num9ActionPerformed

    private void jButton_Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num0ActionPerformed
        String a = txt_cal.getText() + jButton_Num0.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num0ActionPerformed

    private void jButton_Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num8ActionPerformed
        String a = txt_cal.getText() + jButton_Num8.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num8ActionPerformed

    private void jButton_Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Num4ActionPerformed
        String a = txt_cal.getText() + jButton_Num4.getText();
        txt_cal.setText(a);
    }//GEN-LAST:event_jButton_Num4ActionPerformed

    private void jButton_Clear_CalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear_CalculatorActionPerformed
        txt_cal.setText(null);
        txt_cal.grabFocus();
    }//GEN-LAST:event_jButton_Clear_CalculatorActionPerformed

    private void jButton_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SumActionPerformed

        firstnum = Double.parseDouble(txt_cal.getText());
        txt_cal.setText("");
        operations = "+";
        txt_cal.grabFocus();
        
    }//GEN-LAST:event_jButton_SumActionPerformed

    private void jButton_MinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MinessActionPerformed

        firstnum = Double.parseDouble(txt_cal.getText());
        txt_cal.setText("");
        operations = "-";
        txt_cal.grabFocus();
        
    }//GEN-LAST:event_jButton_MinessActionPerformed

    private void jButton_SubstractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubstractionActionPerformed

        firstnum = Double.parseDouble(txt_cal.getText());
        txt_cal.setText("");
        operations = "*";
        txt_cal.grabFocus();
        
    }//GEN-LAST:event_jButton_SubstractionActionPerformed

    private void jButton_DevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DevisionActionPerformed

        firstnum = Double.parseDouble(txt_cal.getText());
        txt_cal.setText("");
        operations = "/";
        txt_cal.grabFocus();
        
    }//GEN-LAST:event_jButton_DevisionActionPerformed

    private void jButton_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EqualActionPerformed

        String answer;
        secondnum = Double.parseDouble(txt_cal.getText());

        if (operations == "+") {
            result = firstnum + secondnum;
            answer = String.format("%.0f",result);
            txt_cal.setText(answer);
            txt_cal.setText(answer);
            
        }

        else if (operations == "-") {
            result = firstnum - secondnum;
            answer = String.format("%.0f",result);
            txt_cal.setText(answer);
        }

        else if (operations == "*") {
            result = firstnum * secondnum;
            answer = String.format("%.0f",result);
            txt_cal.setText(answer);
        }

        else if (operations == "/") {
            result = firstnum / secondnum;
            answer = String.format("%.0f",result);
            txt_cal.setText(answer);
        }

        else if (operations == "%") {
            result = firstnum % secondnum;
            answer = String.format("%.0f",result);
            txt_cal.setText(answer);
        }
    }//GEN-LAST:event_jButton_EqualActionPerformed

    private void jButton_Plua_Or_MinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Plua_Or_MinessActionPerformed
        double op = Double.parseDouble(String.valueOf(txt_cal.getText()));
        op = op * (-1);
        txt_cal.setText(String.valueOf(op));
        txt_cal.grabFocus();
    }//GEN-LAST:event_jButton_Plua_Or_MinessActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void txt_calKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_calKeyTyped

          char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
                
            evt.consume();
            getToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_calKeyTyped

    private void jLabel_MiniimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseClicked

        this.setState(JFrame_20.ICONIFIED);
    }//GEN-LAST:event_jLabel_MiniimizeMouseClicked

    private void jLabel_MiniimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0,153,255));
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(new Color(0,153,255));
    }//GEN-LAST:event_jLabel_MiniimizeMouseEntered

    private void jLabel_MiniimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MiniimizeMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_Miniimize.setBorder(Lable__Border);
        jLabel_Miniimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_MiniimizeMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseEntered

        Border Lable__Border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.RED);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.RED);
    }//GEN-LAST:event_jLabel_CloseMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited

        Border Lable__Border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_Close.setBorder(Lable__Border);
        jLabel_Close.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_CloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Clear_Calculator;
    private javax.swing.JButton jButton_Devision;
    private javax.swing.JButton jButton_Dot;
    private javax.swing.JButton jButton_Equal;
    private javax.swing.JButton jButton_Miness;
    private javax.swing.JButton jButton_Num0;
    private javax.swing.JButton jButton_Num1;
    private javax.swing.JButton jButton_Num2;
    private javax.swing.JButton jButton_Num3;
    private javax.swing.JButton jButton_Num4;
    private javax.swing.JButton jButton_Num5;
    private javax.swing.JButton jButton_Num6;
    private javax.swing.JButton jButton_Num7;
    private javax.swing.JButton jButton_Num8;
    private javax.swing.JButton jButton_Num9;
    private javax.swing.JButton jButton_Plua_Or_Miness;
    private javax.swing.JButton jButton_Substraction;
    private javax.swing.JButton jButton_Sum;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Miniimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_cal;
    // End of variables declaration//GEN-END:variables
}