/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management_system;

import static hospital_management_system.JFrame_11.jLabel_Date;
import static hospital_management_system.JFrame_11.jLabel_Time;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author All in one
 */
public class JFrame_17 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_17
     */
    public JFrame_17() {
        initComponents();
        showTableData();
        showDate();
        showTime();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }  
    
    //Date and Time

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - YYYY");
        jLabel_Date.setText(s.format(d));
    }

    void showTime() {

        new Timer(0, (ActionEvent e) -> {
            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss a");
            jLabel1_Time.setText(s.format(d));
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1_Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jTextField_Total_Cost = new javax.swing.JTextField();
        jButton_Clear = new javax.swing.JButton();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Period = new javax.swing.JTextField();
        jTextField_Cost_Medicine = new javax.swing.JTextField();
        jTextField_Cost_Vehicales = new javax.swing.JTextField();
        jTextField_Cost_Salaries = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Cost_Maintaince = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_New1 = new javax.swing.JMenuItem();
        jMenuItem_Open_Cal1 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Close1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details of monthly expenses in hospital");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Hospital_Management_System/Expenditure dollar-icon.png"))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details of monthly expenses in hospital");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 930, 50);

        jLabel1_Time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_Time.setText("Time :-");
        jPanel1.add(jLabel1_Time);
        jLabel1_Time.setBounds(30, 130, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ID Nunber :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 200, 120, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Period :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 260, 70, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost for Medicine :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 320, 168, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cost for Vehicales :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 380, 173, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Cost for Salaries :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 440, 158, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Cost of Maintaince :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 500, 179, 22);

        jButton_Add.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add.setText("Add");
        jButton_Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add);
        jButton_Add.setBounds(190, 620, 120, 40);

        jButton_Delete.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Delete.setText("Delete");
        jButton_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Delete);
        jButton_Delete.setBounds(340, 620, 120, 40);

        jButton_Update.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Update.setText("Update");
        jButton_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Update);
        jButton_Update.setBounds(500, 620, 120, 40);

        jButton_Search.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Search.setText("Search");
        jButton_Search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Search);
        jButton_Search.setBounds(820, 620, 120, 40);

        jButton_Back.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("<<Back");
        jButton_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Back);
        jButton_Back.setBounds(30, 620, 120, 40);

        jTextField_Total_Cost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Total_Cost);
        jTextField_Total_Cost.setBounds(230, 560, 190, 30);

        jButton_Clear.setBackground(new java.awt.Color(0, 84, 140));
        jButton_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Clear.setText("Clear");
        jButton_Clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear);
        jButton_Clear.setBounds(660, 620, 120, 40);

        jTextField_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_ID);
        jTextField_ID.setBounds(230, 200, 190, 30);

        jTextField_Period.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Period);
        jTextField_Period.setBounds(230, 260, 190, 30);

        jTextField_Cost_Medicine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Cost_Medicine);
        jTextField_Cost_Medicine.setBounds(230, 320, 190, 30);

        jTextField_Cost_Vehicales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Cost_Vehicales);
        jTextField_Cost_Vehicales.setBounds(230, 380, 190, 30);

        jTextField_Cost_Salaries.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Cost_Salaries);
        jTextField_Cost_Salaries.setBounds(230, 440, 190, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Total Cost :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 560, 110, 22);

        jTextField_Cost_Maintaince.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField_Cost_Maintaince);
        jTextField_Cost_Maintaince.setBounds(230, 500, 190, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 200, 470, 390);

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Date.setText("Date :-");
        jPanel1.add(jLabel_Date);
        jLabel_Date.setBounds(690, 130, 230, 29);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\My Java Projects\\Hospital_Management_System\\Images\\ian-dooley-DuBNA1QMpPA-unsplash.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 940, 660);

        jMenu2.setText("File");

        jMenuItem_New1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_New1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/New-file-icon.png"))); // NOI18N
        jMenuItem_New1.setText("New");
        jMenuItem_New1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_New1jMenuItem_NewActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_New1);

        jMenuItem_Open_Cal1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Open_Cal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Scientific-calculator-icon.png"))); // NOI18N
        jMenuItem_Open_Cal1.setText("Open Calculator");
        jMenuItem_Open_Cal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Open_Cal1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Open_Cal1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Home-icon.png"))); // NOI18N
        jMenuItem1.setText("Go Back to Home Page");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem_Close1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Exit-icon.png"))); // NOI18N
        jMenuItem_Close1.setText("Close");
        jMenuItem_Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Close1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Close1);
        jMenu2.add(jSeparator2);

        jMenuItem1_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management_system/Logout-icon.png"))); // NOI18N
        jMenuItem1_logout.setText("Logout");
        jMenuItem1_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_logoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1_logout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed

        if (jTextField_ID.getText().trim().isEmpty() && jTextField_Period.getText().trim().isEmpty() && jTextField_Cost_Maintaince.getText().trim().isEmpty() && jTextField_Cost_Medicine.getText().trim().isEmpty() && jTextField_Cost_Salaries.getText().trim().isEmpty() && jTextField_Cost_Vehicales.getText().trim().isEmpty() && jTextField_Total_Cost.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Period.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Maintaince.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Medicine.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Salaries.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Vehicales.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Total_Cost.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before the updating.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "UPDATE expenditure_details SET Period=? ,Cost_for_Medicine=? ,Cost_for_Vehicales=? ,Cost_for_Salaries=? ,Cost_of_Maintaince=? ,Total_Cost=? WHERE ID_Nunber=?";//query wka ewnass wenawa ekinekata

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(7, jTextField_ID.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(1, jTextField_Period.getText());
                pst.setString(2, jTextField_Cost_Medicine.getText());
                pst.setString(3, jTextField_Cost_Vehicales.getText());
                pst.setString(4, jTextField_Cost_Salaries.getText());
                pst.setString(5, jTextField_Cost_Maintaince.getText());
                pst.setString(6, jTextField_Total_Cost.getText());
                pst.executeUpdate();

                System.out.println(query);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Updated Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_17.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            jTextField_Cost_Maintaince.setText(null);
            jTextField_Cost_Medicine.setText(null);
            jTextField_Cost_Salaries.setText(null);
            jTextField_Cost_Vehicales.setText(null);
            jTextField_ID.setText(null);
            jTextField_Period.setText(null);
            jTextField_Total_Cost.setText(null);
            jTextField_ID.grabFocus();

        }
        showTableData();
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed

        int a;
        a = a = JOptionPane.showConfirmDialog(null, "Are you sure to you went to clear the data?", "Clear Data.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

            jTextField_Cost_Maintaince.setText(null);
            jTextField_Cost_Medicine.setText(null);
            jTextField_Cost_Salaries.setText(null);
            jTextField_Cost_Vehicales.setText(null);
            jTextField_ID.setText(null);
            jTextField_Period.setText(null);
            jTextField_Total_Cost.setText(null);
            jTextField_ID.grabFocus();

        }
        showTableData();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed

        if (jTextField_ID.getText().trim().isEmpty() && jTextField_Period.getText().trim().isEmpty() && jTextField_Cost_Maintaince.getText().trim().isEmpty() && jTextField_Cost_Medicine.getText().trim().isEmpty() && jTextField_Cost_Salaries.getText().trim().isEmpty() && jTextField_Cost_Vehicales.getText().trim().isEmpty() && jTextField_Total_Cost.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Period.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Maintaince.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Medicine.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Salaries.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Cost_Vehicales.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField_Total_Cost.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter data to all feilds before add data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                String query = "INSERT INTO expenditure_details(ID_Nunber, Period, Cost_for_Medicine, Cost_for_Vehicales, Cost_for_Salaries, Cost_of_Maintaince, Total_Cost)VALUES(?,?,?,?,?,?,?)";

                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextField_ID.getText());//query eke adala feild eka yedi athi place eke number eka merhanadi parameeeter eka lesa yediya yuthuya.
                pst.setString(2, jTextField_Period.getText());
                pst.setString(3, jTextField_Cost_Medicine.getText());
                pst.setString(4, jTextField_Cost_Vehicales.getText());
                pst.setString(5, jTextField_Cost_Salaries.getText());
                pst.setString(6, jTextField_Cost_Maintaince.getText());
                pst.setString(7, jTextField_Total_Cost.getText());

                pst.executeUpdate();

                System.out.println(pst);
                System.out.println("1 row affected");

                JOptionPane.showMessageDialog(null, "Data Inserted Succsessfully!!!");

                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_17.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

            }

            jTextField_Cost_Maintaince.setText(null);
            jTextField_Cost_Medicine.setText(null);
            jTextField_Cost_Salaries.setText(null);
            jTextField_Cost_Vehicales.setText(null);
            jTextField_ID.setText(null);
            jTextField_Period.setText(null);
            jTextField_Total_Cost.setText(null);
            jTextField_ID.grabFocus();

        }

        showTableData();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        if (jTextField_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the ID Nunber before delete data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:mysql://localhost:3306/";
                String db = "hospital_management_system_database";
                String user = "root";
                String pword = "123456";

                Connection con = null;
                con = DriverManager.getConnection(url + db, user, pword);

                int a;
                a = JOptionPane.showConfirmDialog(null, "Are you sure to you went delete that record in databasse", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

                if (a == 0) {

                    String query = "DELETE FROM expenditure_details WHERE ID_Nunber=?";

                    PreparedStatement pst = con.prepareStatement(query);

                    pst.setString(1, jTextField_ID.getText());
                    pst.executeUpdate();

                    jTextField_Cost_Maintaince.setText(null);
                    jTextField_Cost_Medicine.setText(null);
                    jTextField_Cost_Salaries.setText(null);
                    jTextField_Cost_Vehicales.setText(null);
                    jTextField_ID.setText(null);
                    jTextField_Period.setText(null);
                    jTextField_Total_Cost.setText(null);
                    jTextField_ID.grabFocus();

                    System.out.println(pst);
                    System.out.println("1 row affected");

                    JOptionPane.showMessageDialog(null, "Record Deleted Succsessftlly...");

                }
                con.close();

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {

                Logger.getLogger(JFrame_17.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_ID.setText(null);
                jTextField_ID.grabFocus();

            }

        }
        showTableData();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed

        if (jTextField_ID.getText().trim().isEmpty()) {

            getToolkit().beep();

            JOptionPane.showMessageDialog(null, "You should enter the ID Nunber before Search data into the database.", "Warnimg!!!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String url = "jdbc:mysql://localhost:3306/"; //url
                String db = "hospital_management_system_database"; //Database Name
                String user = "root";//user name
                String pword = "123456"; //password

                System.out.println(jTextField_ID.getText());//search kirimata yoda gannna textbox eke variabale name eka.
                Connection con = null;
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance(); //driver
                con = DriverManager.getConnection(url + db, user, pword);

                //SQL Query
                String sql = "SELECT * FROM expenditure_details WHERE ID_Nunber = '" + jTextField_ID.getText() + "'";

                ResultSet res = con.createStatement().executeQuery(sql);
                System.out.println(sql);

                while (res.next()) {

                    /* System.out.println(res.getString("Patient_Name"));
                System.out.println(res.getString("Doctor_Name"));*/
                    jTextField_Period.setText(res.getString("Period"));  //Text feild wala names ewa form eke athi piliwelata yodanna.
                    jTextField_Cost_Medicine.setText(res.getString("Cost_for_Medicine"));
                    jTextField_Cost_Vehicales.setText(res.getString("Cost_for_Vehicales"));
                    jTextField_Cost_Salaries.setText(res.getString("Cost_for_Salaries"));
                    jTextField_Cost_Maintaince.setText(res.getString("Cost_of_Maintaince"));
                    jTextField_Total_Cost.setText(res.getString("Total_Cost"));

                    System.out.println(res.getString("ID_Nunber") + " " + res.getString("Total_Cost"));
                    System.out.println("Row Affected");
                    //Vadagthma field deke names yodanna.

                }

                con.close();//Connection eka close kirima.

            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

                Logger.getLogger(JFrame_17.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);

                jTextField_Cost_Maintaince.setText(null);
                jTextField_Cost_Medicine.setText(null);
                jTextField_Cost_Salaries.setText(null);
                jTextField_Cost_Vehicales.setText(null);
                jTextField_ID.setText(null);
                jTextField_Period.setText(null);
                jTextField_Total_Cost.setText(null);
                jTextField_ID.grabFocus();

            }
        }
        showTableData();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //TABALES SHOULD BE ENABLED FIRST
        //Table eka click karahama data pennwimata.
        
        int rows = jTable1.getRowCount();

        if (rows != 0) {

            int row_selected = jTable1.getSelectedRow();

            String id = jTable1.getValueAt(row_selected, 0).toString();
            String period = jTable1.getValueAt(row_selected, 1).toString();
            String medicine = jTable1.getValueAt(row_selected, 2).toString();
            String vehicales = jTable1.getValueAt(row_selected, 3).toString();
            String salaries = jTable1.getValueAt(row_selected, 4).toString();
            String maintaince = jTable1.getValueAt(row_selected, 5).toString();
            String total = jTable1.getValueAt(row_selected, 6).toString();

            jTextField_ID.setText(id);
            jTextField_Period.setText(period);
            jTextField_Cost_Medicine.setText(medicine);
            jTextField_Cost_Vehicales.setText(vehicales);
            jTextField_Cost_Salaries.setText(salaries);
            jTextField_Cost_Maintaince.setText(maintaince);
            jTextField_Total_Cost.setText(total);

        } else {

            JOptionPane.showMessageDialog(null, rows);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem_New1jMenuItem_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_New1jMenuItem_NewActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you save that data?", "Go to new form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == 0) {

           jTextField_Cost_Maintaince.setText(null);
            jTextField_Cost_Medicine.setText(null);
            jTextField_Cost_Salaries.setText(null);
            jTextField_Cost_Vehicales.setText(null);
            jTextField_ID.setText(null);
            jTextField_Period.setText(null);
            jTextField_Total_Cost.setText(null);
            jTextField_ID.grabFocus();

        }
    }//GEN-LAST:event_jMenuItem_New1jMenuItem_NewActionPerformed

    private void jMenuItem_Open_Cal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Open_Cal1ActionPerformed

        JFrame_18 f18 = new JFrame_18();
        f18.setVisible(true);
    }//GEN-LAST:event_jMenuItem_Open_Cal1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFrame_5 f5 = new JFrame_5();
        f5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Close1ActionPerformed

        int b;
        b = JOptionPane.showConfirmDialog(null, "Are you sure to close the program now?", "Close the program...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (b == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem_Close1ActionPerformed

    private void jMenuItem1_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_logoutActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(null, "Are you sure to you want to logout the program.", "Logout the system.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (a == 0) {

            this.dispose();
            JFrame_10 f10 = new JFrame_10();
            f10.setVisible(true);

        }
    }//GEN-LAST:event_jMenuItem1_logoutActionPerformed

    public void showTableData() {

        try {

            String url = "jdbc:mysql://localhost:3306/";
            String db = "hospital_management_system_database";
            String user = "root";
            String pword = "123456";

            Connection con = null;
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url + db, user, pword);

            String query = "SELECT * FROM expenditure_details;";

            PreparedStatement pst = con.prepareStatement(query);
            ResultSet res = con.createStatement().executeQuery(query);

            pst = con.prepareStatement(query);
            res = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
                       
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {

            Logger.getLogger(JFrame_17.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_17().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1_Time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1_logout;
    private javax.swing.JMenuItem jMenuItem_Close1;
    private javax.swing.JMenuItem jMenuItem_New1;
    private javax.swing.JMenuItem jMenuItem_Open_Cal1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Cost_Maintaince;
    private javax.swing.JTextField jTextField_Cost_Medicine;
    private javax.swing.JTextField jTextField_Cost_Salaries;
    private javax.swing.JTextField jTextField_Cost_Vehicales;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Period;
    private javax.swing.JTextField jTextField_Total_Cost;
    // End of variables declaration//GEN-END:variables
}
